trainer:
  model_name: "resnet18"
  pretrained: False

  train_freeze_layers: []
  freeze_layers: False
  n_epochs: 10
  minimizer: "asam" # ASAM, SAM
  optimizer: "sgd" # nado adam, lion, sgd i hvatit ya schitayu
  lr_scheduler: "reduce_lr" # cosine, reduce_lr
  criterion: "crossentropy"
  classification_type: "onevsall"

  max_lr: !!float 5e-2
  min_lr: !!float 1e-4

  ckpt_load: ~
  ckpt_dir: "./ckpts"
  batch_size: 12
  save_interval: 1

  scheduler_cfg: # config dlya reducelronplateaeaeaeau
    mode: "min"
    factor: 0.05
    patience: 2
    threshold: 0.0001
    threshold_mode: "rel"
    cooldown: 0
    min_lr: !!float 1e-12
    eps: !!float 1e-8

  # scheduler_cfg: # config dlya cosine
  #   T_max: 5
  #   eta_min: !!float 3e-6

  minimizer_cfg:
    rho: 0.05
    eta: !!float 1e-8

  opt_cfg:
    lr: !!float 3e-3
    momentum: 0.09

  augmentations: False
  train_log_interval: 1
  val_log_interval: 2

validation_intermediate:
  validate: True
  interval: 1

validation_final:
  validate: False
  testset: "val"
